apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-udagram
  labels:
    app: frontend-udagram
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend-udagram
  template:
    metadata:
      labels:
        app: frontend-udagram
    spec:
      containers:
        - name: frontend-udagram
          image: tcart79/udagram-frontend:latest
          imagePullPolicy: Always
          resources:
            requests:
              memory: "128Mi"
              cpu: "300m"
            limits:
              memory: "1024Mi"
              cpu: "600m"
          ports:
            - containerPort: 8100