apiVersion: v1
kind: Service
metadata:
  name: udagram-frontend-svc
  labels:
    service: udagram-frontend
spec:
  ports:
  - name: "80"
    port: 80
    targetPort: 80
  selector:
    service: udagram-frontend