apiVersion: v1
kind: Service
metadata:
  name: reverseproxy-svc
  labels:
    service: reverseproxy
spec:
  ports:
  - name: "8080"
    port: 8080
    targetPort: 8080
  selector:
    service: reverse-proxy